Vagrant::Config.run do |config|
  config.vm.box = "precise64ruby19"
  config.vm.customize ["modifyvm", :id, "--memory", 5000]
#  config.vm.network :hostonly, "192.168.111.113"
 config.vm.network :bridged
# Glassfish/webapp ports
  config.vm.forward_port 8080, 8888
  config.vm.forward_port 8181, 8111
  config.vm.forward_port 8686, 6868
  config.vm.forward_port 4848, 8484
# Mysql server port
  config.vm.forward_port 3306, 3333
# Ndb ports
  config.vm.forward_port 10001, 10001
  config.vm.forward_port 10002, 10002
  config.vm.forward_port 10003, 10003
  config.vm.forward_port 10004, 10004
  config.vm.forward_port 10005, 10005
  config.vm.forward_port 10006, 10006
# Chef ports
  config.vm.forward_port 4000, 40000
  config.vm.forward_port 4040, 40400
  config.vm.forward_port 8983, 89830

  #Collectd network plugin
  config.vm.forward_port 25826,55826,{ :protocol => "udp"}

   config.vm.provision :chef_solo, :log_level => :debug do |chef|
     chef.log_level = :debug
     chef.cookbooks_path = "cookbooks"
     chef.add_recipe "authbind"
     chef.add_recipe "java"
     chef.add_recipe "mysql"
     chef.add_recipe "openssh"
     chef.add_recipe "openssl"
     chef.add_recipe "glassfish::kthfs"
     chef.add_recipe "collectd::server"
     chef.add_recipe "kthfsagent"
     chef.add_recipe "ndb::mgmd"
     chef.add_recipe "ndb::ndbd"
     chef.add_recipe "ndb::mysqld"
     chef.add_recipe "ndb::memcached"
     chef.add_recipe "ndb::mgmd-kthfs"
     chef.add_recipe "ndb::ndbd-kthfs"
     chef.add_recipe "ndb::mysqld-kthfs"
     chef.add_recipe "ndb::memcached-kthfs"
     chef.add_recipe "chefserver"
     chef.add_recipe "chefserver::ironfan"
     chef.add_recipe "chefserver::ec2"
#     chef.add_recipe "ndb::mysqld-install"
#     chef.add_recipe "ndb::memcached-install"
  end 

end
