Vagrant::Config.run do |config|
  config.vm.box = "precise64"
#  config.vm.box = "quantal64"

  config.vm.customize ["modifyvm", :id, "--memory", 5000]
# config.vm.network :hostonly, "192.168.111.113"
  config.vm.network :bridged
# Ndb ports
  config.vm.forward_port 10001, 10001
  config.vm.forward_port 10002, 10002
  config.vm.forward_port 10003, 10003
  config.vm.forward_port 10004, 10004
  config.vm.forward_port 10005, 10005
  config.vm.forward_port 10006, 10006
#Memcached - ndb
  config.vm.forward_port 11211, 11211

   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.log_level = :debug

#     chef.add_recipe "kthfsagent"

     chef.add_recipe "ndb::mgmd"
     chef.add_recipe "ndb::ndbd"
     chef.add_recipe "ndb::mysqld"
     chef.add_recipe "ndb::memcached"
#     chef.add_recipe "collectd::client"
#     chef.add_recipe "ndb::mgmd-kthfs"
#     chef.add_recipe "ndb::ndbd-kthfs"
#     chef.add_recipe "ndb::mysqld-kthfs"
#     chef.add_recipe "ndb::memcached-kthfs"
  end 

end
