#!/bin/sh
#
# Startup script for ndbd
#
### BEGIN INIT INFO
# Provides:                     ndb_node-*
# Required-Start:                 
# Should-Start:                 
# Required-Stop:                  
# Default-Start:                2 3 4 5
# Default-Stop:                 0 1 6
# Short-Description:            start and stop ndb_node-*
# Description:                  Start/Stop/Restart NDB Data Node: ndb_node-*
### END INIT INFO

# Variables
#prog="#{node[:mysql][:base_dir]}/bin/ndbd"
#START_PROG="$prog -c #{node[:ndb][:connect_string]} --ndb-nodeid=#{node[:ndb][:id]} > #{node[:ndb][:logs_dir]}/ndb_#{node[:ndb][:id]}.log 2>&1 > /dev/null &"

INIT_PROG=<%= node[:ndb][:base_dir] %> + "/scripts/init-start-ndbd.sh"
START_PROG=<%= node[:ndb][:base_dir] %> + "/scripts/start-noinit-ndbd.sh"
STOP_PROG=<%= node[:ndb][:base_dir] %> + "/scripts/stop-ndbd.sh"
RESTART_PROG=<%= node[:ndb][:base_dir] %> + "/scripts/restart-ndbd.sh"


RETVAL=0

EXEC_WITH_USER="su <%= node[:ndb][:user] %> -c"

init() {
  echo "Executing as '<%= node[:ndb][:user] %>': $INIT_PROG"
  $EXEC_WITH_USER "$INIT_PROG"
  return $?
}


start() {
  echo "Executing as '<%= node[:ndb][:user] %>': $START_PROG"
  $EXEC_WITH_USER "$START_PROG"
  return $?
}

stop() {
  $EXEC_WITH_USER "$STOP_PROG"

  PID_FILE=<%= node[:ndb][:logs_dir] + "/ndb_" + node[:ndb][:id] + ".pid" %> 
  PROCESS_ID=`cat $PID_FILE`
  echo "Shutting down"
  kill $PROCESS_ID

  wait_pid_removed=10
  timeout=0
  while [ $timeout -lt $wait_pid_removed ] ; do
    sleep 1
    test ! -s $PID_FILE && break
    echo -n "."
    timeout=`expr $timeout + 1`
  done
  echo ""

  return $?
}

restart() {
  echo "Executing as 'root': $RESTART_PROG"

  $EXEC_WITH_USER "$RESTART_PROG"

  return $?
}


# user-supplied parameter to stop/start/restart process.
case "$1" in
  init)
    init
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  reload)
    restart
    ;;
  -h|--help)
    echo ""
    echo "usage: <prog> start|stop|restart"
    echo ""
    exit 0
    ;;
  *)
    echo $"Usage: <prog> {start|stop|restart}"
    exit 1
  esac


exit $RETVAL
